### ISSUE TITLE
Make plugin key configured on module level

### ISSUE THREAD

**Issue by pawelniewie** [MeisterLabs/atlassian-jwt-authentication#17]
Current API requires controller to pass plugin key, any reason this can't be configured on module level as other config options? Do you handle multiple addons with a single rails server?

If you don't why don't we move it there and remove the previous API?

If you do handle multiple addons with a single process why don't we support both (module level and controller level)?

**Comment by bulinutza** [comment]
Hi Pawel,

Yes, we handle 2 addons with a single server...

**Comment by bulinutza** [comment]
I'm fine with being able to support both, but what would be the advantage
of that?

**Comment by pawelniewie** [comment]
Cleaner way to invoke JWT authentication in the controller (you could use a simple named filter instead of using send et all). But knowing you need to support multiple addons per server I'm not that eager to fix it.

**Comment by bulinutza** [comment]
Ok :-)
