### ISSUE TITLE
on_add_on_uninstalled handler fails because data['context'] is nil

### ISSUE THREAD

**Issue by pawelniewie** [MeisterLabs/atlassian-jwt-authentication#3]
Hi Laura,
quick question - I'm getting an error handling uninstalls:

```
NoMethodError (undefined method `[]' for nil:NilClass):

/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/atlassian-jwt-authentication-d95917a63251/lib/atlassian-jwt-authentication/filters.rb:145:in `_verify_jwt'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/atlassian-jwt-authentication-d95917a63251/lib/atlassian-jwt-authentication/filters.rb:42:in `on_add_on_uninstalled'
```

As far as I can see data has only following fields:
`data = {"iss"=>"connection:308548", "iat"=>1464724702, "qsh"=>"8a8d06f040b246544d605b08aeb419e30b5cf0e200f512888486585ecce6a52e", "aud"=>"connection:308548", "exp"=>1468324702}`

Have you noticed something like that? I wonder what could be the problem.

**Comment by bulinutza** [comment]
Hi Pawel,

it seems that there is no data['context'] in there. What Atlassian product
are you using this with?

**Comment by pawelniewie** [comment]
I'm using BitBucket. So that worked correctly with other products?

**Comment by bulinutza** [comment]
I hadn't tested it with BitBucket, it's possible that they don't send a
user context. I will check it and update the gem accordingly :-)

**Comment by bulinutza** [comment]
This is now fixed with the latest version. Please read the README carefully on the newly required structure for the models, you might need to re-run the generator for this newer version. I've also added support for making a service call.

**Comment by pawelniewie** [comment]
Wow, that's awesome! I owe you a 🍺 ! :-)
