### ISSUE TITLE
Query parameters not checked?

### ISSUE THREAD

**Issue by tbu** [MeisterLabs/atlassian-jwt-authentication#9]
Hi Laura,

Within my iframe I present links to the user pointing back to my add-on server to retrieve further resources. To secure these links they have an individual jwt token attached. The token is created as such:

`jwt = JWT.encode({
                         qsh: qsh,
                         iat: issued_at,
                         exp: expires_at,
                         iss: current_jwt_auth.client_key
                     }, current_jwt_auth.shared_secret)`

For the query hash string I explicitly take the url parameters into account:

`qsh = Digest::SHA256.hexdigest("#{method.to_s.upcase}&#{endpoint}&#{parameters}")
`

The token generated is valid as verified by https://jwt-decoder.herokuapp.com/jwt/decode. Also, your gem verifies the incoming requests just fine. 

However, when I manually alter the query parameters in the url (e.g. changing https://abc.com/bla?c=d&jwt=123 to https://abc.com/bla?c=E&jwt=123) I would except the verify_jwt filter to fail - which it doesn't. 

Any idea why this doesn't work? Is it a problem with the gem or am I making a mistake creating the JWT token?

Thanks!

**Comment by bulinutza** [comment]
Hi there,

Sorry for the late response, I've been away on business.
Are you using the verify_jwt filter for the action that receives the incoming request from the example URL ( https://abc.com/bla?c=d&jwt=123 ) ?

**Comment by bulinutza** [comment]
tbu, I just tested a bit and you're right, the second URL should fail. I will add an update for this and let you know.

**Comment by bulinutza** [comment]
Hi again, tbu. This is now fixed. Please take a look at the updated documentation as well, for setting the context_path configuration if you need it for your addon.
